server:
  port: 7700
mail:
  sender: FreyRaum <admin@freya.fitness>
  develop:
    receiver: develop@freya.fitness
  template:
    DEFAULT: E-Mail von freya.fitness
    CONTACT: Kontaktanfrage freya.fitness
    RESET_PASSWORD: Passwort für freya.fitness zurücksetzen